"""initial schema

Revision ID: f60999013389
Revises:
Create Date: 2026-05-27 22:06:45.592373

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f60999013389"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "pdf_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("processing_status", sa.String(length=32), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("classification_error", sa.Text(), nullable=True),
        sa.Column("classified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parsing_error", sa.Text(), nullable=True),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(op.f("ix_pdf_documents_user_id"), "pdf_documents", ["user_id"], unique=False)
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "pdf_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pdf_document_id", sa.String(length=36), nullable=False),
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("run_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["pdf_document_id"], ["pdf_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pdf_document_id", name="uq_pdf_jobs_pdf_document_id"),
    )
    op.create_index(
        op.f("ix_pdf_jobs_pdf_document_id"), "pdf_jobs", ["pdf_document_id"], unique=False
    )
    op.create_index(
        "ix_pdf_jobs_pending_poll", "pdf_jobs", ["status", "run_after", "created_at"], unique=False
    )
    op.create_table(
        "pdf_page_extracts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pdf_document_id", sa.String(length=36), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("extractor", sa.String(length=64), nullable=False),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["pdf_document_id"], ["pdf_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "pdf_document_id",
            "page_number",
            "extractor",
            name="uq_pdf_page_extracts_doc_page_extractor",
        ),
    )
    op.create_index(
        op.f("ix_pdf_page_extracts_pdf_document_id"),
        "pdf_page_extracts",
        ["pdf_document_id"],
        unique=False,
    )
    op.create_table(
        "pdf_pages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pdf_document_id", sa.String(length=36), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("page_class", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("signals_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["pdf_document_id"], ["pdf_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pdf_document_id", "page_number", name="uq_pdf_pages_doc_page"),
    )
    op.create_index(
        op.f("ix_pdf_pages_pdf_document_id"), "pdf_pages", ["pdf_document_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pdf_pages_pdf_document_id"), table_name="pdf_pages")
    op.drop_table("pdf_pages")
    op.drop_index(op.f("ix_pdf_page_extracts_pdf_document_id"), table_name="pdf_page_extracts")
    op.drop_table("pdf_page_extracts")
    op.drop_index("ix_pdf_jobs_pending_poll", table_name="pdf_jobs")
    op.drop_index(op.f("ix_pdf_jobs_pdf_document_id"), table_name="pdf_jobs")
    op.drop_table("pdf_jobs")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_pdf_documents_user_id"), table_name="pdf_documents")
    op.drop_table("pdf_documents")
    op.drop_table("users")
    # ### end Alembic commands ###
